"""Ajusta CategoriaModel para usar UUID e created_at

Revision ID: 61f2871e1c75
Revises: e4698425249e
Create Date: 2025-08-05 14:46:01.050548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f2871e1c75'
down_revision: Union[str, Sequence[str], None] = 'e4698425249e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categorias', 'created_at')
    # ### end Alembic commands ###
