"""Adiciona created_at ao centro_treinamento

Revision ID: e4698425249e
Revises: 51d4c56c9e20
Create Date: 2025-08-05 14:24:49.492176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4698425249e'
down_revision: Union[str, Sequence[str], None] = '51d4c56c9e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centros_treinamento', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('centros_treinamento', 'created_at')
    # ### end Alembic commands ###
